
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERROGACION = 16;
  public static final int GUION = 7;
  public static final int PUNTO = 11;
  public static final int PERCENT = 13;
  public static final int CADENA = 2;
  public static final int OR = 12;
  public static final int LETRA = 21;
  public static final int RCONJ = 17;
  public static final int FLECHA = 8;
  public static final int MAYORQUE = 9;
  public static final int KLEENE = 15;
  public static final int CARACTER = 22;
  public static final int COMA = 18;
  public static final int EOF = 0;
  public static final int DIGITO = 20;
  public static final int CHAREX = 3;
  public static final int RANGO4 = 26;
  public static final int ESPECIAL = 27;
  public static final int RANGO3 = 25;
  public static final int error = 1;
  public static final int LLAVE2 = 5;
  public static final int RANGO2 = 24;
  public static final int LLAVE1 = 4;
  public static final int RANGO1 = 23;
  public static final int IDENTIFICADOR = 19;
  public static final int DOSPTS = 6;
  public static final int PTYCOMA = 10;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "CHAREX",
  "LLAVE1",
  "LLAVE2",
  "DOSPTS",
  "GUION",
  "FLECHA",
  "MAYORQUE",
  "PTYCOMA",
  "PUNTO",
  "OR",
  "PERCENT",
  "MAS",
  "KLEENE",
  "INTERROGACION",
  "RCONJ",
  "COMA",
  "IDENTIFICADOR",
  "DIGITO",
  "LETRA",
  "CARACTER",
  "RANGO1",
  "RANGO2",
  "RANGO3",
  "RANGO4",
  "ESPECIAL"
  };
}

